/**
 * Honest rewrites of the old comparison posts. Facts about competitors come from
 * the competitors' own pages as retrieved on 2026-10-07 (see SEO_BATCH1_A5_REPORT.md);
 * nothing here is a claimed test, a quote, or a statistic we cannot source.
 * Section shapes: {h2}, {p}, {ul:[…]}, {table:{head:[…],rows:[[…]]}}, {note}.
 */
const V = 'October 7, 2026';

module.exports = [
  {
    file: 'rezi-vs-resumetailored',
    tag: 'Tool Comparison',
    title: 'Rezi vs ResumeTailored AI (2026): Pricing, Free Plans and Features',
    description: 'Rezi and ResumeTailored AI compared on free plans, price, lifetime deals and cover letters, using Rezi’s own pricing page as checked on October 7, 2026.',
    ogDescription: 'Rezi ($29/mo, $149 lifetime) vs ResumeTailored AI ($19.00/mo, $129 lifetime): what each free plan includes, with sources.',
    readMin: 6,
    stats: [['$29', 'Rezi Pro, per month'], ['$19.00', 'ResumeTailored Pro, per month'], ['$149 / $129', 'Lifetime: Rezi / ResumeTailored']],
    body: [
      { p: 'Rezi is an established AI resume builder with a free plan, a monthly plan and a lifetime option. ResumeTailored AI is built around one job: taking your resume and a job posting and tailoring the resume and cover letter to that posting. Both can be useful. This comparison sticks to what each company publishes, and says where we could not confirm something.' },
      { note: `Facts about Rezi below come from Rezi’s own pricing page, checked ${V}. Prices change, so confirm on rezi.ai before you buy.` },
      { h2: 'Plans and prices' },
      { table: { head: ['', 'Rezi', 'ResumeTailored AI'], rows: [
        ['Free plan', 'Free: 1 resume, 1 AI interview, 3 PDF downloads, limited AI keyword targeting; unlimited cover letters (per its FAQ)', 'Free account: unlimited resume tailoring, cover letters and ATS scans; 6 templates; exports carry a small watermark'],
        ['Monthly', 'Pro $29/month: unlimited resumes, AI interviews and PDF downloads, full AI keyword targeting, one expert resume review a month', 'Pro $19.00/month: 3 tailoring variants per job, ATS rewrite report, all 104 templates, watermark-free exports'],
        ['Lifetime', '$149 one-time (Pro features, no included monthly expert review)', '$129 one-time (includes 30 tailoring-variant sets per month)'],
        ['Refunds', '30-day money-back guarantee on Pro and Lifetime', 'Monthly plans cancel any time; Lifetime is a one-time purchase'],
      ] } },
      { h2: 'What Rezi does well' },
      { ul: ['A free plan that includes unlimited cover letters and an AI interview, plus a published 30-day money-back guarantee.', 'A lifetime plan with Pro features and no stated monthly cap on use.', 'A monthly expert resume review on Pro, which is a human check on top of the software.', 'Team and enterprise options for organisations (Enterprise is $99 per month per 200 users).'] },
      { h2: 'Where ResumeTailored AI is different' },
      { ul: ['Unlimited tailoring on the free plan: with a free account you can tailor a resume and cover letter to every posting you apply to.', 'Job-URL import: paste a link from LinkedIn, Indeed, Glassdoor or 40+ other job boards and the posting is pulled in. We could not confirm whether Rezi offers this, so check Rezi’s site.', 'A lower monthly price ($19.00 versus $29) and a lower lifetime price ($129 versus $149), with the lifetime plan carrying a 30-variant-set monthly cap.', 'English and Chinese interface, and translation of non-English resumes.'] },
      { h2: 'What we are not claiming' },
      { p: 'We have not verified which AI model Rezi uses, and we have not published a controlled test of writing quality, so this post makes no claim that either tool writes better. If output quality matters to you, the fair test is simple: run the same resume and the same job posting through both free plans and read the results side by side.' },
      { h2: 'Which should you use?' },
      { p: 'Choose Rezi if you want a builder with interview practice, an expert-review option and a long money-back window. Choose ResumeTailored AI if you apply to many roles and want each resume and cover letter tailored to the posting without a cap on the free plan. Many people try both free plans first.' },
    ],
    sources: ['https://www.rezi.ai/pricing'],
  },
  {
    file: 'teal-vs-resumetailored',
    tag: 'Tool Comparison',
    title: 'Teal vs ResumeTailored AI (2026): Job Tracker or Tailoring Tool?',
    description: 'Teal and ResumeTailored AI compared: Teal’s free tracker and credit-limited AI versus unlimited tailoring, with prices checked on October 7, 2026.',
    ogDescription: 'Teal (free tracker, Teal+ $29/30 days) vs ResumeTailored AI ($19.00/mo): what each free plan includes, with sources.',
    readMin: 6,
    stats: [['$29', 'Teal+ per 30 days'], ['$19.00', 'ResumeTailored Pro, per month'], ['Unlimited', 'Free tailoring on ResumeTailored']],
    body: [
      { p: 'Teal and ResumeTailored AI start from different places. Teal is a job-search workspace: a resume builder, a job tracker and AI helpers in one account. ResumeTailored AI centres on tailoring a resume and cover letter to each posting. They overlap, and plenty of people could reasonably use both.' },
      { note: `Facts about Teal come from Teal’s pricing page and help center, retrieved ${V}. Confirm current limits on tealhq.com; plans change.` },
      { h2: 'Plans and prices' },
      { table: { head: ['', 'Teal', 'ResumeTailored AI'], rows: [
        ['Free plan', 'Unlimited resumes and job tracking, 10 templates, basic analysis, keyword matching for the top 5 only, 10 AI credits for bullets and 2 each for a summary and a cover letter', 'Free account: unlimited resume tailoring, cover letters and ATS scans; 6 templates; small export watermark'],
        ['Paid', 'Teal+: $13 per week, $29 per 30 days or $79 per 90 days (about $26.33 a month); no annual plan', 'Pro $19.00/month; Lifetime $129 one-time'],
        ['AI cover letters', '2 credits on Free; unlimited on Teal+', 'Unlimited on Free'],
        ['Job tracker', 'Core feature, unlimited on Free', 'Free tracker, up to 20 applications on the free plan'],
        ['Job-URL import', 'Check official site', '40+ job boards by URL'],
      ] } },
      { h2: 'Where Teal is stronger' },
      { ul: ['A full job-search workspace: unlimited tracking of applications and contacts on the free plan.', 'More free templates (10 versus our 6) and unlimited resume editing and export.', 'Short billing periods (weekly, 30-day and 90-day; no annual plan), handy for a short search.'] },
      { h2: 'Where ResumeTailored AI is stronger' },
      { ul: ['AI tailoring and cover letters are not credit-limited on the free plan.', 'A lower paid price: $19.00 a month versus $29 per 30 days (about $26.33 a month at the 90-day price) for Teal+, plus a $129 lifetime option.', 'Start from a job URL on 40+ job boards instead of copying the description.'] },
      { h2: 'Using both' },
      { p: 'Tracking and tailoring are different jobs. A reasonable setup is to track applications in Teal (or our own free tracker), and tailor each resume and cover letter in ResumeTailored AI. Nothing locks you in: tailored documents export as PDF, DOCX or text.' },
      { h2: 'What we are not claiming' },
      { p: 'We do not claim anything about which AI model Teal uses or which tool writes better, and we have not published a test that would support such a claim. Compare them yourself on the same resume and posting.' },
    ],
    sources: ['https://www.tealhq.com/pricing', 'https://help.tealhq.com/en/articles/9530153-teal-vs-teal'],
  },
  {
    file: 'jobscan-vs-resumetailored',
    tag: 'Tool Comparison',
    title: 'Jobscan vs ResumeTailored AI (2026): Scanning vs Rewriting',
    description: 'Jobscan scores a resume against a job; ResumeTailored AI also rewrites it. Prices, free limits and cover-letter tools compared, checked October 7, 2026.',
    ogDescription: 'Jobscan ($49.95/mo, 5 free scans) vs ResumeTailored AI ($19.00/mo, unlimited free tailoring): what each includes, with sources.',
    readMin: 6,
    stats: [['$49.95', 'Jobscan Premium, monthly'], ['$19.00', 'ResumeTailored Pro, per month'], ['5', 'Jobscan free scans per month']],
    body: [
      { p: 'Jobscan built its name on the resume-to-job-description match report. ResumeTailored AI starts from the same problem but goes one step further and rewrites the resume and cover letter for the posting. Which fits you depends on whether you want a diagnosis or a draft.' },
      { note: `Facts about Jobscan were verified ${V} against jobscan.co. Its pricing page sits behind a login, so confirm current prices, limits and refund terms on the site before you buy.` },
      { h2: 'Plans and prices' },
      { table: { head: ['', 'Jobscan', 'ResumeTailored AI'], rows: [
        ['Free plan', '5 match scans per month, a free resume builder and a job tracker', 'Free account: unlimited tailoring, cover letters and ATS scans'],
        ['Paid', 'Premium: $49.95 per month, $89.95 per quarter (about $29.98 a month) or about $24.95 a month billed annually ($299.40 a year); 7-day trial', 'Pro $19.00/month; Lifetime $129 one-time'],
        ['Premium extras', 'Unlimited scans, AI optimizations (desktop only), AI Cover Letter Generator, LinkedIn optimization. Auto Apply launched June 2026 and runs on paid credits', 'ATS rewrite report, 3 tailoring variants, all 104 templates, resume video, personal website'],
        ['Job-URL import', 'Check official site', '40+ job boards by URL'],
        ['Refunds', '2-calendar-day window, unused plans only, 3.5% fee (check official site)', 'Cancel any time from your account'],
      ] } },
      { h2: 'Where Jobscan is stronger' },
      { ul: ['A dedicated, long-established scanner with a detailed match report and recruiter and ATS findings.', 'LinkedIn optimization and a cover-letter scanner on Premium, plus a 7-day trial.', 'If a score against one job description is all you need, five free scans a month may be enough.'] },
      { h2: 'Where ResumeTailored AI is stronger' },
      { ul: ['Tailoring is unlimited on the free plan, and scanning and rewriting happen in one flow.', 'A lower paid price ($19.00 versus $49.95 monthly, about $29.98 on Jobscan’s quarterly plan or about $24.95 a month annually).', 'Free ATS scanner plus a Pro report showing the keyword changes and a before/after match score.'] },
      { h2: 'How the match score works' },
      { p: 'Jobscan’s match rate is keyword overlap with the job description, not a simulation of how a real applicant tracking system will rank you. Our own ATS scan is also an estimate. Treat either as a guide to missing keywords, not a verdict.' },
      { h2: 'What we are not claiming' },
      { p: 'Jobscan lists AI optimizations and an AI cover letter generator on Premium, so we do not describe it as scan-only. We have not tested which tool’s keyword matching is more accurate. Run one resume and one posting through both and compare.' },
    ],
    sources: ['https://app.jobscan.co/plan'],
  },
  {
    file: 'why-rezi-cover-letters-fall-short',
    tag: 'Tool Comparison',
    title: 'Rezi Cover Letters: What the Free Plan Includes and How to Judge Them',
    description: 'What Rezi’s free plan says about cover letters, how ResumeTailored AI approaches them, and a simple checklist for judging any AI-written cover letter.',
    ogDescription: 'Rezi’s free plan lists unlimited cover letters. Here is how to evaluate any AI cover letter, and how ours works.',
    readMin: 5,
    stats: [['Unlimited', 'Rezi cover letters on Free (per Rezi)'], ['Unlimited', 'ResumeTailored cover letters on Free'], ['5', 'Checks to judge any cover letter']],
    body: [
      { p: 'This post originally argued that Rezi’s cover letters fall short. We could not support that with evidence we can cite, and Rezi’s own pricing page lists unlimited cover letters on its free plan. So we have replaced it with something more useful: what is actually offered, and how to judge any AI-written cover letter yourself.' },
      { note: `Rezi information is from rezi.ai/pricing, checked ${V}.` },
      { h2: 'What each tool offers' },
      { ul: ['Rezi: unlimited cover letters on the free plan and on paid plans (per Rezi’s FAQ and plan comparison).', 'ResumeTailored AI: a cover letter is generated alongside the tailored resume from the same job description, unlimited with a free account.'] },
      { h2: 'Five checks for any AI cover letter' },
      { ul: ['Is the first sentence about this job and company, or could it open any letter? Replace generic openers.', 'Does it name two or three requirements from the posting and answer each with a real example from your experience?', 'Are the facts yours? Remove any claim, number or skill you cannot defend in an interview.', 'Is it under one page, with a clear close and a reason you want this role?', 'Does it sound like you? Read it aloud and cut anything you would never say.'] },
      { h2: 'How ResumeTailored AI approaches it' },
      { p: 'The letter is generated from your resume and the job posting together, so it can refer to the posting’s own requirements. It is a draft: you should still read it against the checklist above and edit it. We keep every claim tied to what is in your resume.' },
      { h2: 'The fair test' },
      { p: 'If you are deciding between tools, paste the same resume and posting into each tool’s free plan and score the letters with the checklist. That tells you more than any vendor comparison, including this one.' },
    ],
    sources: ['https://www.rezi.ai/pricing'],
  },
  {
    file: 'why-claude-writes-better-resumes',
    tag: 'AI Technology',
    title: 'Claude vs ChatGPT for Resumes: How to Compare Them Yourself',
    description: 'ResumeTailored AI uses Anthropic’s Claude. Here is what that means, what we have and have not tested, and a practical method to compare AI models for a resume.',
    ogDescription: 'We use Claude for resume tailoring. This guide explains what we do and do not claim, and how to compare models fairly.',
    readMin: 6,
    stats: [['Claude', 'Model used by ResumeTailored AI'], ['0', 'Controlled studies we have published'], ['1', 'Fair test: same resume, same posting']],
    body: [
      { p: 'ResumeTailored AI is powered by Anthropic’s Claude. An earlier version of this post claimed that we blind-tested Claude against ChatGPT with recruiters and that Claude won. We do not have a published, citable study, so we have removed those claims. Here is what we can honestly say, and how to run your own comparison.' },
      { h2: 'What we can say' },
      { ul: ['We chose Claude for resume tailoring because it works well for us on this task. That is a product decision, not a published benchmark.', 'Both Claude and ChatGPT can write usable resume content, and results vary by model version and by prompt.', 'The biggest quality factor is the input: a specific resume, a specific posting and clear instructions beat any model choice.'] },
      { h2: 'What good AI resume writing looks like' },
      { ul: ['Specific: names the tools, scale and outcome from your real experience instead of generic phrases.', 'True: adds no skills, employers or numbers that are not in your original resume.', 'Matched: uses the job posting’s own terms where they apply to you, without stuffing keywords.', 'Readable: plain, active sentences a recruiter can scan quickly.'] },
      { h2: 'A fair way to compare models yourself' },
      { ul: ['Pick one resume and one job posting.', 'Give each tool the same inputs and ask for the same outputs (a tailored summary, three bullets and a cover letter).', 'Score each output against the four qualities above, ideally with a friend who does not know which is which.', 'Check every claim against your real history. Any invented detail is a reason to reject the output.'] },
      { h2: 'Guardrails matter more than the model' },
      { p: 'Whatever model you use, review the result. AI tools can introduce details that were not in your resume. You are the one who has to explain it in an interview, so edit anything you cannot stand behind.' },
    ],
    sources: [],
  },
  {
    file: 'free-ats-resume-scanners-compared',
    tag: 'Tool Roundup',
    title: 'Free ATS Resume Scanners Compared (2026): What Each Free Plan Includes',
    description: 'What Jobscan, Teal, Resume Worded and ResumeTailored AI include on their free plans, with sources and dates. Limits change, so confirm before relying on them.',
    ogDescription: 'A sourced look at the free tiers of four ATS resume scanners as of October 7, 2026.',
    readMin: 6,
    stats: [['4', 'Free scanners compared'], ['5', 'Jobscan free scans a month'], ['Unlimited', 'ResumeTailored free scans']],
    body: [
      { p: 'Applicant tracking system (ATS) scanners compare your resume with a job description and flag missing keywords and formatting issues. Most have a free tier with limits. Below is what each publishes, with where the information came from. We are one of the four, so read our row with that in mind.' },
      { note: `Facts retrieved ${V} from each company’s own pages (Jobscan’s plan page, Teal’s pricing page and help center, Resume Worded’s tool pages). Free limits change often and some pages disagree with each other; confirm on each site.` },
      { table: { head: ['Tool', 'Free tier', 'What the free tier is best for'], rows: [
        ['Jobscan', '5 match scans per month plus a free resume builder', 'Detailed match reports when you only need a few'],
        ['Teal', 'Keyword matching limited to the top 5, basic analysis, unlimited resumes and job tracking, 10 AI credits for bullets', 'Organising a search and a basic keyword check'],
        ['Resume Worded', 'Free tools (Score My Resume, Targeted Resume); its pages do not state one clear monthly cap, so check its site', 'Instant score and line-by-line feedback'],
        ['ResumeTailored AI', 'Unlimited ATS scans and unlimited tailoring with a free account; Pro adds an ATS rewrite report', 'Scanning and rewriting in one flow'],
      ] } },
      { h2: 'How to choose' },
      { ul: ['If you want a score only and apply to a few jobs a month, any free tier may be enough.', 'If you apply to many roles, check the monthly limit first.', 'If you want the rewrite as well as the diagnosis, check whether the tool rewrites on the free plan or only scores.', 'If LinkedIn matters, check which tool includes LinkedIn optimization on its free plan. Our free LinkedIn optimizer gives a score and all suggestions.'] },
      { h2: 'A caution about ATS statistics' },
      { p: 'You will see claims that a large share of resumes are rejected by ATS software before a human sees them. Those figures are widely repeated and poorly sourced. What is well established is simpler: plain structure, standard headings and the posting’s own terms make a resume easier for software and for people to read.' },
    ],
    sources: ['https://app.jobscan.co/plan', 'https://www.tealhq.com/pricing', 'https://resumeworded.com/'],
  },
  {
    file: 'resumetailored-vs-canva',
    tag: 'Tool Comparison',
    title: 'ResumeTailored vs Canva for Resumes: Design Tool or Tailoring Tool?',
    description: 'Canva is a design app with resume templates; ResumeTailored AI tailors a resume to a job posting. When each makes sense, plus how to check any resume for ATS readability.',
    ogDescription: 'Canva for visual design, ResumeTailored AI for tailoring: how to choose, and how to test any resume for ATS readability.',
    readMin: 6,
    stats: [['Free', 'Unlimited tailoring on ResumeTailored'], ['$19.00', 'ResumeTailored Pro, per month'], ['$129', 'ResumeTailored lifetime (one-time)']],
    body: [
      { p: 'Canva is a general design tool, and many people build a resume in it because the templates look good and the editor is easy to use. ResumeTailored AI does something narrower: it takes your resume and a job posting and tailors the resume and cover letter to that posting. They solve different problems, so this is less a head-to-head than a guide to when each one fits.' },
      { note: 'We could not retrieve Canva’s current pricing or feature pages for this update, so this post makes no claims about Canva’s prices or what its AI tools can and cannot do. Check canva.com for current details.' },
      { h2: 'Where Canva fits' },
      { ul: ['A visually distinctive resume or one-page profile for a creative role, a portfolio, or a networking event.', 'Any situation where a person, not software, will look at the design first.', 'Matching your resume’s look to other design work: business cards, a portfolio, a personal brand.'] },
      { h2: 'Where ResumeTailored AI fits' },
      { ul: ['Applying to many roles, where you want the resume and a cover letter adjusted to each posting.', 'Applications that go through an applicant tracking system, where plain structure and the posting’s own terms help.', 'Free, unlimited tailoring with an account; Pro at $19.00 a month or a $129 lifetime plan adds more templates, variants and watermark-free exports.'] },
      { h2: 'The one thing to test whichever tool you use: ATS readability' },
      { p: 'Applicant tracking systems read your resume as text. Layouts that rely on columns, text boxes, icons, skill bars or images can be read out of order or skipped by some parsers. Standard headings and a simple single-column flow are the safest choice. You can check any resume yourself:' },
      { ul: ['Export to PDF or DOCX and copy all the text into a plain-text editor. Is it in a sensible order, with your name, employers, dates and skills intact?', 'Run it through a free ATS scanner, including ours, and see whether your name, contact details and job titles are extracted correctly.', 'Keep a plain, single-column version for online applications and a designed version for sharing in person.'] },
      { h2: 'A note on ATS myths' },
      { p: 'You may have read that most resumes are auto-rejected by ATS software. That figure is widely repeated and poorly sourced, and many recruiters say their system does not auto-reject. The practical risk is quieter: a garbled parse can make your application harder to find and read. The fix is the same: clean structure, standard headings, and the posting’s own terms.' },
      { h2: 'Which should you use?' },
      { p: 'Use Canva when design is the point. Use ResumeTailored AI when getting a tailored, readable resume and cover letter out fast is the point. Plenty of people do both: tailor the content here, and design a separate visual version elsewhere if they need one.' },
    ],
    sources: [],
  },
];
