module.exports = {
  slug: 'resume-writing-for-accountants',
  who: 'accountants',
  badge: 'Accounting',
  linkLabel: 'Resume writing for accountants',
  title: 'How to Write an Accountant Resume: CPA, GAAP & ERP Keywords',
  meta: 'How to write an accountant resume: list your CPA and other credentials, show close and reconciliation results, and use the GAAP, ERP and Excel keywords.',
  h1: 'Resume Writing for Accountants: A Step-by-Step Guide',
  keywords_meta: 'how to write an accountant resume, accounting resume guide, cpa on resume, accounting resume keywords, staff accountant resume bullets',
  intro: 'Accounting hiring is credential- and accuracy-driven. A controller or recruiter checks your license and your systems first, then looks for evidence that you close on time, reconcile cleanly and work with auditors. Your resume should be exact, and it should show it.',
  screeners: [
    'Your license or certification status: CPA, CMA, EA or an exam in progress, with the state where relevant.',
    'The size and type of what you handled: entities, transaction volume, revenue range, industry and reporting framework.',
    'Core process ownership: month-end close, reconciliations, accounts payable or receivable, payroll, tax or audit support.',
    'The systems: the ERP and accounting software you use, and your Excel depth.',
    'Accuracy and control: audit results, adjustments, internal-control work and compliance such as Sarbanes-Oxley.',
  ],
  licensureTitle: 'Licenses and certifications: how to list them',
  licensure: [
    { name: 'CPA (Certified Public Accountant)', how: 'Licensing is regulated by each state board of accountancy and usually requires a set number of education credits (commonly 150 semester hours), the Uniform CPA Exam and experience. List “CPA, [State], active” after your name and under Certifications. Rules vary by state, so confirm with your board.' },
    { name: 'CPA candidate', how: 'If you are mid-exam, write “CPA candidate: passed [sections], remaining [sections] expected [month year]”. Be precise and truthful; it signals progress and is common for staff-level roles.' },
    { name: 'Other credentials', how: 'List the CMA (Certified Management Accountant), EA (Enrolled Agent, authorised by the IRS), CIA (internal audit) or CFE where relevant, with the year earned.' },
    { name: 'Education', how: 'State your degree, school and graduation year. Include a master’s in accounting or taxation if you have one, since it can count toward CPA education requirements.' },
  ],
  keywords: [
    { label: 'Core accounting', terms: ['GAAP', 'month-end close', 'general ledger', 'journal entries', 'account reconciliation', 'accruals', 'fixed assets', 'accounts payable', 'accounts receivable', 'financial statements'] },
    { label: 'Analysis, audit and tax', terms: ['variance analysis', 'budgeting and forecasting', 'audit support', 'internal controls', 'SOX', 'tax preparation', 'sales tax', 'consolidation', 'cost accounting'] },
    { label: 'Systems', terms: ['QuickBooks', 'NetSuite', 'SAP', 'Oracle', 'Workday Financials', 'Excel pivot tables', 'XLOOKUP', 'ERP', 'Power BI'] },
  ],
  keywordTip: { a: 'accounts payable', b: 'AP' },
  walkthrough: [
    { h: 'Header and credentials', body: 'Name, then credentials such as CPA, plus contact details and city. Hiring teams for accounting roles often filter by location and license, so state both.' },
    { h: 'Summary: scope, framework, systems', body: 'Two to three lines naming your level, the kind of company, the volume you handle and your systems.', example: 'CPA with [X] years in corporate accounting at a $[X]M manufacturer. Owns month-end close, AP and fixed-asset accounting in NetSuite, with a record of clean audits.' },
    { h: 'Credentials block', body: 'Place Licenses and Certifications directly below the summary: license, state, status and year. This is the first thing a controller checks.' },
    { h: 'Experience: ownership, scale, accuracy', body: 'Start each role with the company size and your scope: revenue, number of entities, transaction volume, and the processes you own. Bullets should show speed and accuracy, such as days to close, reconciliations completed, adjustments or audit findings, and process improvements. Say what you automated and what it saved.', example: 'Shortened month-end close from [X] to [X] business days by standardizing reconciliations and automating accruals in NetSuite, with zero audit adjustments for [X] consecutive quarters.' },
    { h: 'Controls and compliance', body: 'Add a bullet on internal controls, audit support, SOX testing or tax compliance if relevant. Hiring managers value an accountant who knows how things are checked.' },
    { h: 'Skills: systems and Excel', body: 'List the accounting software and ERP by exact name, then Excel skills such as pivot tables, XLOOKUP or VLOOKUP, and Power Query, if you use them. Group them so the ATS finds them.' },
    { h: 'Format and length', body: 'One page up to about ten years; two pages for senior and controller roles. Use a conventional single-column layout and consistent formatting; accountants are expected to be tidy.' },
  ],
  mistakes: [
    'Hiding the license status. Write “CPA, [State], active” or your exam progress clearly.',
    'Listing “QuickBooks” for a role that needs an ERP, or listing no systems at all.',
    'Describing duties without volume: “reconciled accounts” says nothing without the number of accounts or entities.',
    'Typos and inconsistent formats, which are especially costly in this field.',
    'Forgetting to mention audit and controls experience for roles that need them.',
    'Claiming Excel proficiency with no examples; name the functions you use.',
  ],
  boards: {
    intro: 'Accounting roles come through company career pages, firm recruiting sites and staffing firms. Larger employers commonly use applicant tracking systems such as Workday or iCIMS, which parse your resume and let recruiters search by license and software names, so spell out credentials and systems exactly.',
    items: [
      'Company career pages and LinkedIn, which many corporate finance teams use for hiring.',
      'Accounting and finance staffing firms for temp-to-hire and seasonal roles, especially around year-end and tax season.',
      'Firm and university recruiting for entry-level positions; apply early in the recruiting cycle.',
      'Tailor your summary to the posting’s industry (nonprofit, manufacturing, SaaS), since the accounting issues differ.',
    ],
  },
  faq: [
    ['How do I list a CPA license on a resume?', 'Put “CPA” after your name and add “Certified Public Accountant, [State], active” under Certifications with the year. Include the license number only if an application asks for it.'],
    ['How do I show my CPA exam progress?', 'List the sections you have passed and when you expect to finish the rest: “CPA candidate: passed AUD and FAR; BEC and REG scheduled for [month year]”. Only list what is true.'],
    ['What is the best way to show my accuracy?', 'Use measurable controls: reconciliations completed, close time, audit adjustments, error rates, or compliance results. If you do not have a number, describe the control you ran.'],
    ['Which software should I list?', 'The ERP and accounting systems you use daily, by exact name, plus Excel skills. Match the posting’s names, such as NetSuite or SAP, and avoid listing tools you have only seen.'],
    ['How long should an accountant resume be?', 'One page for staff-level and entry-level accountants, and two pages for managers and controllers.'],
  ],
  related: ['resume-writing-for-project-managers', 'resume-writing-for-customer-service-representatives'],
  example: { href: '/accountant-resume', label: 'accountant resume tailoring page' },
  cta: { h: 'Tailor your accounting resume to each posting', t: 'Paste your resume and the posting. We match the credentials, systems and wording the role asks for to your real experience, keep every claim true, and write a matching cover letter.' },
};
