module.exports = {
  slug: 'resume-writing-for-electricians',
  who: 'electricians',
  badge: 'Electrical trades',
  linkLabel: 'Resume writing for electricians',
  title: 'How to Write an Electrician Resume: License, NEC & Skills',
  meta: 'How to write an electrician resume: list your apprenticeship, journeyman or master license, show NEC and project experience, and use the trade keywords.',
  h1: 'Resume Writing for Electricians: A Step-by-Step Guide',
  keywords_meta: 'how to write an electrician resume, electrician resume guide, journeyman electrician resume, electrician resume skills, how to list electrical license on resume',
  intro: 'Electrical contractors hire on license, safety and the kind of work you have done. An electrician’s resume should state your license level up front, describe the projects and systems you have worked on, and make your safety record clear.',
  screeners: [
    'License level and jurisdiction: apprentice, journeyman or master, and the state or local authority.',
    'The type of work: residential, commercial, industrial, service, or low-voltage and controls.',
    'Code and safety knowledge: the National Electrical Code (NEC), arc-flash and lockout/tagout practice, and OSHA training.',
    'Hands-on skills: conduit bending, wire pulling, panel and switchgear work, troubleshooting and reading blueprints.',
    'Reliability: tenure, attendance, a valid driver’s license, and your own tools.',
  ],
  licensureTitle: 'Licenses and training: how to list them',
  licensure: [
    { name: 'Apprenticeship', how: 'Most electricians train through a registered apprenticeship, commonly four to five years combining paid on-the-job hours with classroom instruction, run by programs such as IBEW/NECA joint apprenticeship committees or merit-shop programs. List the program, your year of training and the hours completed, for example “IBEW apprenticeship, 4th year, 6,500 hours completed”.' },
    { name: 'Journeyman or master license', how: 'Licensing is set by each state or local jurisdiction and the rules differ, so check yours. List the level, the issuing authority, the license status and the expiry: “Journeyman Electrician, [State], active through [year]”. Add the number only if the application requests it. Master or contractor licenses go at the top because they open supervisory and business roles.' },
    { name: 'Safety training', how: 'List OSHA 10 or OSHA 30 cards, NFPA 70E arc-flash training, first aid and CPR, and any lift or confined-space training, with dates.' },
    { name: 'Specialty credentials', how: 'Fire alarm, low-voltage, solar, EV-charger or PLC and motor-control training can set you apart. List the credential, the issuer and the year.' },
  ],
  keywords: [
    { label: 'Work and systems', terms: ['commercial wiring', 'industrial electrical', 'residential wiring', 'service calls', 'panel installation', 'switchgear', 'lighting controls', 'generators', 'fire alarm', 'low voltage'] },
    { label: 'Skills', terms: ['NEC', 'conduit bending', 'EMT', 'wire pulling', 'troubleshooting', 'blueprints', 'schematics', 'load calculations', 'grounding', 'motor controls', 'PLC'] },
    { label: 'Safety and credentials', terms: ['journeyman electrician', 'master electrician', 'apprenticeship', 'OSHA 10', 'OSHA 30', 'lockout/tagout', 'arc flash', 'NFPA 70E', 'valid driver’s license'] },
  ],
  keywordTip: { a: 'National Electrical Code', b: 'NEC' },
  walkthrough: [
    { h: 'Header with license level', body: 'Name, phone, email, town and your license level on the line below, for example “Journeyman Electrician, [State]”. Contractors scan for the license first.' },
    { h: 'Summary: level, work type, safety', body: 'Two lines: your license level, years of experience, the kind of work you have done and your safety record.', example: 'Licensed journeyman electrician with [X] years in commercial and industrial installation and service. NEC-proficient, OSHA 30 trained, with [X] years without a recordable incident.' },
    { h: 'Licenses and training block', body: 'List your license, apprenticeship, safety cards and specialty credentials in one short block. Add the jurisdiction and expiry for each license.' },
    { h: 'Experience: projects, systems, scale', body: 'For each employer, give the company, location, dates and the type of work. Use bullets that name the systems and the scale: voltage levels, building size, circuit counts, the type of project, and your role. Add schedule or quality results when you have them, and say if you led a crew or trained apprentices.', example: 'Installed and terminated power and lighting for a [X] sq ft commercial build-out, including [X] panels and [X] feeders, passing inspection on the first visit; led a crew of [X] including [X] apprentices.' },
    { h: 'Show troubleshooting and safety', body: 'Add a bullet that shows how you diagnose problems, such as finding intermittent faults, restoring service, or working on energized equipment under safe procedures. Add one bullet on safety practice and your record.' },
    { h: 'Skills, tools and driving', body: 'List the code you work to, your trade skills and any testing equipment you use, such as multimeters, insulation testers and thermal cameras. Add your driver’s license and whether you have your own tools and a vehicle, if the job needs them.' },
    { h: 'Education and format', body: 'List your high-school diploma or trade school, and training certificates. Keep the resume to one page in a single column. Electrical contractors and union halls often want a clean, simple document.' },
  ],
  mistakes: [
    'Leaving out the license level or jurisdiction, which is the first thing a contractor checks.',
    'Listing “electrical work” without the type of project, voltage level or scale.',
    'Forgetting safety credentials, or listing expired cards.',
    'Naming code editions or standards you do not work to. Name the code in force in your jurisdiction.',
    'Leaving the apprenticeship hours off if you are still training; hours and year of training show progress.',
    'Mixing union referral and contractor applications without tailoring: halls and contractors want different details.',
  ],
  boards: {
    intro: 'Electrical jobs come through several routes: union hiring halls that dispatch members, contractor career pages, and general job boards. Many small contractors read resumes by hand, while larger firms use applicant tracking systems that search for license, trade terms and safety credentials.',
    items: [
      'IBEW local union halls and their referral systems, if you are a member or applying to a program.',
      'Contractor and facility career pages, plus Indeed and ZipRecruiter for trades roles.',
      'Apprenticeship programs run by unions and industry associations, which accept applications at set times.',
      'Referrals from foremen and other trades; keep a clean one-page resume to hand over on the job site.',
    ],
  },
  faq: [
    ['How do I list a journeyman license on a resume?', 'Write the level, the state or local authority, and the status and expiry, for example “Journeyman Electrician, [State], active through [year]”. Add the number only when asked.'],
    ['I am still an apprentice. What goes on the resume?', 'List your program, your year of training, the on-the-job hours and classroom hours completed, and the types of work you have done. Add safety cards and any specialty training.'],
    ['Should I list NEC code knowledge?', 'Yes, and name the code you work to in your jurisdiction. Add specific areas you know well, such as load calculations, grounding or motor controls.'],
    ['How do I show I work safely?', 'List your OSHA cards and arc-flash training, mention lockout/tagout practice, and state your record, such as years without a recordable incident, if it is true.'],
    ['How long should an electrician resume be?', 'One page. Put your license, safety credentials and the projects most similar to the job first.'],
  ],
  related: ['resume-writing-for-warehouse-associates', 'resume-writing-for-project-managers'],
  example: { href: '/electrician-resume', label: 'electrician resume tailoring page' },
  cta: { h: 'Tailor your electrician resume', t: 'Paste your resume and the job posting. We match the license wording, systems and trade skills the posting asks for to your real experience, keep every claim true, and write a matching cover letter.' },
};
