module.exports = {
  slug: 'resume-writing-for-nurses',
  who: 'nurses',
  badge: 'Nursing',
  linkLabel: 'Resume writing for nurses',
  title: 'How to Write a Nurse Resume: Licenses, Keywords, Format',
  meta: 'How to write a nursing resume: list your RN license and certifications, use the right ATS keywords, and show your unit and patient-load detail.',
  h1: 'Resume Writing for Nurses: A Step-by-Step Guide',
  keywords_meta: 'how to write a nurse resume, nursing resume guide, rn resume writing, nursing resume keywords, how to list nursing license on resume',
  intro: 'A nursing resume is screened twice: first by software that checks your license, certifications and clinical keywords, then by a nurse manager who wants to know what kind of unit you have actually worked on. This guide shows how to write for both.',
  screeners: [
    'An active license in the state of the job (or a multistate compact license), listed where a quick scan will find it.',
    'Current life-support certifications, such as BLS and any that the unit requires, with no expired dates.',
    'The kind of unit and patient population you have worked with: bed count, acuity, and nurse-to-patient ratio.',
    'Experience with the charting system the hospital uses, such as Epic, Oracle Health (Cerner) or Meditech.',
    'Evidence that you work safely and improve outcomes: falls, infections, medication errors, patient education and discharge work.',
  ],
  licensureTitle: 'Licenses and certifications: how to list them',
  licensure: [
    { name: 'RN license', how: 'Nurses are licensed by the state board of nursing after passing the NCLEX-RN. Put the state and license status in your header or a dedicated Licensure section, for example “RN, Texas (active)”. If you hold a multistate license under the Nurse Licensure Compact, say so. Add the license number only if the application asks for it.' },
    { name: 'Degree and credentials', how: 'Add your highest nursing degree after your name or in Education (ADN, BSN, MSN). If you are completing a BSN, list the program and expected date rather than leaving it off.' },
    { name: 'Life support', how: 'List BLS, ACLS, PALS, NRP or TNCC as the unit requires, with the issuing body (often the American Heart Association) and the expiry month and year. An expired certification can cost you a screen, so renew first or mark it as “renewal scheduled”.' },
    { name: 'Specialty certifications', how: 'Board certifications such as CCRN (critical care), CEN (emergency) or CMSRN (medical-surgical) belong near the top of the page because they signal your specialty. Spell out the full name once, then use the acronym, so that both versions are matched.' },
  ],
  keywords: [
    { label: 'Clinical', terms: ['patient assessment', 'care plans', 'medication administration', 'IV therapy', 'telemetry', 'wound care', 'central line care', 'ventilator management', 'triage', 'discharge planning', 'patient education'] },
    { label: 'Systems and compliance', terms: ['Epic', 'Oracle Health (Cerner)', 'Meditech', 'EHR', 'MAR', 'HIPAA', 'Joint Commission', 'infection control', 'evidence-based practice', 'electronic charting'] },
    { label: 'Workload and teamwork', terms: ['nurse-to-patient ratio', 'charge nurse', 'preceptor', 'interdisciplinary team', 'rapid response', 'patient advocacy', 'SBAR handoff'] },
  ],
  keywordTip: { a: 'electronic health record', b: 'EHR' },
  walkthrough: [
    { h: 'Header and credentials', body: 'Put your name, then your credentials (for example RN, BSN), phone, email and city and state. Nurse managers hire locally, so your location matters; a state you are licensed in but do not live in is worth a short line such as “Licensed in TX and FL (compact)”. Skip the photo and the full street address.' },
    { h: 'Summary: three lines, specific to your unit', body: 'State your specialty, your years of experience, your patient population and one strength. Avoid adjectives like “compassionate”; hiring managers assume that and ATS gets nothing from it. Say what you do.', example: 'Medical-surgical RN with [X] years on a [X]-bed telemetry unit, carrying a 1:[X] ratio. Epic-proficient, charge-nurse trained, and focused on early recognition of patient decline and clear discharge teaching.' },
    { h: 'Licensure and certifications', body: 'Give this its own short block directly below the summary so a recruiter and the ATS see it in the first seconds. Use one line per item: name, issuing body or state, and expiry. Keep expired items off.' },
    { h: 'Experience: lead with the unit, then the impact', body: 'For each job, write the employer, city, dates and unit on the first line, for example “Memorial Hospital, Austin TX. 32-bed cardiac step-down. 2021 to present”. Then use three to five bullets. Start with the context (patients, ratio, acuity), then what you did, then the result. Count things: patients per shift, falls reduced, preceptees trained, audit scores.', example: 'Cared for [X] post-operative cardiac patients per shift on a 1:[X] ratio; completed [X]% on-time medication passes and cut avoidable falls on the unit by [X]% by leading hourly rounding.' },
    { h: 'Skills section for the ATS', body: 'Group skills in two or three short lines: clinical skills, systems, and specialties. Use the posting’s phrasing, for example “telemetry monitoring” if that is how the posting words it. Only list what you can do on the first day.' },
    { h: 'Education and continuing education', body: 'List your nursing degree, school and graduation year. Add relevant continuing education only if it supports the job, such as wound-care or stroke-certification courses. New graduates should add clinical rotations, with the unit, the hours, and the preceptor’s role, under a Clinical Experience heading.' },
    { h: 'Length and format', body: 'One page is right for new and early-career nurses, and two pages for ten or more years or several specialties. Use a single-column layout, standard headings (Experience, Education, Licensure) and a plain font, so the parser reads your dates and employers correctly.' },
  ],
  mistakes: [
    'Leaving the license state off. A recruiter filtering by state will skip you.',
    'Describing duties instead of context: “provided patient care” says nothing; “1:4 on a 28-bed oncology unit” does.',
    'Listing expired BLS or ACLS certifications.',
    'Dropping the unit type and bed count, which is the first thing a manager looks for.',
    'Using a graphic skills chart or a two-column template that the ATS reads out of order.',
    'Sending the same resume for ICU, ER and clinic jobs. The keywords and the order of your bullets should change with the posting.',
  ],
  boards: {
    intro: 'Most hospital systems take applications through their own career sites, which commonly run on applicant tracking systems such as Workday, iCIMS or Taleo. You can often tell which one from the application link before you start, for example a web address containing “myworkdayjobs” or “icims”. Whatever the system, it will parse your resume into fields, so a simple layout matters.',
    items: [
      'Hospital and health-system career pages: apply here whenever you can, since postings on job boards are copies of them.',
      'General boards such as Indeed and LinkedIn, plus Nurse.com, for wider searches and alerts by specialty.',
      'Travel and per-diem roles go through agency portals, which each ask for your skills checklist and license copy: keep both ready.',
      'Re-read each posting and mirror its unit and system names: “Epic” if the posting says Epic, not “EMR”.',
    ],
  },
  faq: [
    ['Should I put my RN license number on my resume?', 'It is usually not needed on the resume itself. List the state and status, for example “RN, Ohio (active)”, and add the number only when an application form or recruiter asks for it.'],
    ['How long should a nursing resume be?', 'One page for new graduates and nurses with a few years of experience; two pages if you have ten or more years or several specialties. Put the license, certifications and most recent unit on page one.'],
    ['I am a new graduate with no nursing job yet. What goes under Experience?', 'Use a Clinical Experience section: each rotation with the unit type, the hours, the patient population and the skills you performed. Add any CNA, tech or volunteer healthcare work, and your NCLEX status or date.'],
    ['Do I list every certification?', 'List those that are current and relevant to the job. BLS and any unit-required certification go first. Remove anything expired and anything unrelated.'],
    ['How do I show impact if I do not have numbers?', 'Use what you know: ratio, bed count, patients per shift, number of preceptees, audit or survey scores you were told about, and the process you improved. If you do not know a number, describe the change precisely rather than guessing.'],
  ],
  related: ['resume-writing-for-customer-service-representatives', 'resume-writing-for-teachers'],
  example: { href: '/registered-nurse-resume', label: 'registered nurse resume tailoring page' },
  cta: { h: 'Tailor your nursing resume to the posting', t: 'Paste your resume and the job posting. We keep every fact true to your experience and match the posting’s wording, with a matching cover letter. A free account is all you need.' },
};
