module.exports = {
  slug: 'resume-writing-for-teachers',
  who: 'teachers',
  badge: 'Teaching',
  linkLabel: 'Resume writing for teachers',
  title: 'How to Write a Teacher Resume: Certification & Keywords',
  meta: 'Guide to writing a teaching resume: how to list your state certification and endorsements, which district ATS keywords to use, and how to show student growth.',
  h1: 'Resume Writing for Teachers: A Step-by-Step Guide',
  keywords_meta: 'how to write a teacher resume, teaching resume guide, teacher resume keywords, how to list teaching certification on resume, education resume writing',
  intro: 'A principal reads a teaching resume to find three things fast: that you are certified for the grade and subject, that students grew in your classroom, and that you will fit the school. This guide covers how to show each, and how to get through a district’s application software.',
  screeners: [
    'A valid certification or license for the state, grade band and subject, with endorsements listed exactly as the state names them.',
    'Grade levels and subjects taught, and class sizes, including any special populations (special education, English learners, gifted).',
    'Evidence of student growth: assessment results, proficiency gains, reading levels, graduation or pass rates.',
    'Classroom management and school-culture contributions, such as PBIS, advisory, coaching or clubs.',
    'Comfort with the district’s tools and standards: the learning management system, the grade-book, and state standards.',
  ],
  licensureTitle: 'Certification and credentials: how to list them',
  licensure: [
    { name: 'State teaching certificate or license', how: 'Requirements are set by each state’s department of education, so list the state, the certificate type, the grade band, the subject area, and the expiration date, for example “Texas Standard Certificate, English Language Arts and Reading 7-12, valid through 2030”. If you are certified in one state and applying in another, say that you hold a certificate in the first state and add “reciprocity application in progress” only if it is true.' },
    { name: 'Endorsements and specializations', how: 'Special education, English as a second language (ESL/ESOL/TESOL), reading specialist, gifted and bilingual endorsements are in high demand and often screened on. Put each one on its own line using the state’s exact name.' },
    { name: 'Exams and portfolios', how: 'Many states require subject exams such as the Praxis series, or a state-specific exam, and some require a performance assessment such as edTPA. List what the posting asks for, with the pass date. If you are still testing, write “Praxis II English, scheduled [month year]”.' },
    { name: 'Clearances and safety training', how: 'Background clearance and fingerprinting are usually handled after an offer, but you can note “current background clearance” if you have one. CPR and first-aid certification is worth a line for early-childhood and physical-education roles.' },
    { name: 'National Board Certification', how: 'If you hold it, put it next to your name or in the first few lines. It is a strong signal for experienced teachers.' },
  ],
  keywords: [
    { label: 'Instruction', terms: ['differentiated instruction', 'lesson planning', 'curriculum mapping', 'backward design', 'small-group instruction', 'formative assessment', 'summative assessment', 'data-driven instruction', 'state standards'] },
    { label: 'Students and support', terms: ['IEP', '504 plan', 'English learners', 'MTSS', 'RTI', 'PBIS', 'social-emotional learning', 'classroom management', 'parent communication'] },
    { label: 'Tools', terms: ['Google Classroom', 'Canvas', 'Schoology', 'SMART Board', 'Seesaw', 'PowerSchool', 'Illuminate', 'EdTech'] },
  ],
  keywordTip: { a: 'individualized education program', b: 'IEP' },
  walkthrough: [
    { h: 'Header and certification line', body: 'Put your name and contact details on top, then one line with your certification, grade band and subject. Principals and HR staff check this line first, so make it unmistakable. A link to a portfolio or class site is optional.', example: 'Certified Elementary Teacher (Grades K-6), [State]. ESL endorsement. [X] years in Title I classrooms.' },
    { h: 'Summary: grade, subject, approach, one proof point', body: 'Three lines at most. Say what you teach, how you teach it, and one result. Avoid “passionate educator”; show the passion with the proof.', example: 'Fourth-grade teacher with [X] years of experience in a [X]-student, inclusion classroom. Uses small-group instruction and weekly data reviews to raise reading growth; [X]% of students met or exceeded their growth targets.' },
    { h: 'Certification and endorsements block', body: 'List each credential on its own line with the state, type, grade band and expiry. This is the block an application system and a human both look for. Keep it above Experience.' },
    { h: 'Experience: students, standards, results', body: 'For each school, give the school name, district, city, grade or subject and years. Under it, three to five bullets that start with a number or a population. Name the standards or program (for example “Common Core aligned” or a state’s standards), the tools, and the result. Student growth is the strongest evidence you can add: benchmark gains, reading level movement, proficiency rates, or pass rates, in your own classroom’s data.', example: 'Raised the share of students reading on grade level from [X]% to [X]% in one year using guided reading groups and bi-weekly running records.' },
    { h: 'Contributions beyond the classroom', body: 'Include coaching, mentoring student teachers, department or grade-team lead, curriculum committees, clubs, and family-engagement events. Keep each to a line with a number or an outcome.' },
    { h: 'Skills and tools', body: 'Group your instructional approaches and technology into two short lines. Match the district’s tool names (for example the LMS and the student information system) when you know them.' },
    { h: 'Education and length', body: 'Give your degree, school, and graduation year, plus any graduate coursework in the subject area. One page is standard for early-career teachers; two pages are acceptable with substantial leadership and results. Use a single-column layout so the district’s system reads each field.' },
  ],
  mistakes: [
    'Listing only “Teacher” and a duty list. Say which grade, subject, class size and student population.',
    'Leaving out certification details, or putting them at the bottom of page two.',
    'Using vague claims such as “improved student outcomes” with no number or source.',
    'Forgetting endorsements that the posting names, such as special education or ESL.',
    'Describing teaching philosophy at length; keep that for the cover letter.',
    'Using a photo or a decorative template; many districts’ systems will mis-read the layout.',
  ],
  boards: {
    intro: 'Most districts accept applications through a school-specific system, and many use an education hiring platform such as Frontline Education (formerly AppliTrack). These systems often ask for your certification information in form fields, then attach your resume, so the form entries and the resume should match.',
    items: [
      'District human-resources sites: the main source of public school openings; check each district’s own job page.',
      'State and regional education boards, such as EDJOIN in California, plus SchoolSpring and K12JobSpot in some regions.',
      'Charter and private school networks usually hire through their own career pages or general boards like Indeed.',
      'Apply early in the spring hiring season, and tailor the opening line to the school’s program, such as dual language or STEM.',
    ],
  },
  faq: [
    ['Should a teacher resume be one page?', 'One page is the norm for new and early-career teachers. Two pages are fine if you have many years, leadership roles and strong data to show. Do not shrink the font below a readable size to force one page.'],
    ['How do I list a certification from another state?', 'List it with the issuing state and type, and state clearly where you are in the process of getting one in the new state, if you are. Do not imply you hold a certificate you do not have.'],
    ['I am a student teacher or new graduate. What do I put under Experience?', 'Lead with your student-teaching placement: school, grade, subject, mentor’s role, and what you taught. Add tutoring, camp, substitute and paraprofessional work, and the lessons or units you designed.'],
    ['How can I show student growth without sharing student data?', 'Use aggregate numbers only, such as class-level proficiency or growth percentages, and never include names or identifying details.'],
    ['Do I need to list the Praxis or state exams?', 'Include the exams the posting or state requires and your pass status. If the posting does not mention exams, a line under certification is enough.'],
  ],
  related: ['resume-writing-for-nurses', 'resume-writing-for-customer-service-representatives'],
  example: { href: '/teacher-resume', label: 'teacher resume tailoring page' },
  cta: { h: 'Tailor your teaching resume to each school', t: 'Paste your resume and the posting. We align your certifications, grade level and methods to the district’s wording, keep every claim true, and write a matching cover letter.' },
};
