import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import { ClerkProvider, ClerkLoading } from "@clerk/nextjs";
import { enUS, zhCN, esES, hiIN, frFR } from "@clerk/localizations";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { resolveLocale, type Locale } from "@/i18n/locales";
import { LoadingScreen } from "@/components/loading-screen";
import { PlanPreviewBanner } from "@/components/plan-preview-banner";
import { PWAProvider } from "@/components/pwa/pwa-context";
import "./globals.css";

/** Clerk's own bundled translations for its widgets (sign-in/up, user/org
 *  profile, the account-switcher, etc.) — separate from next-intl's
 *  messages/*.json, which cover this app's own UI chrome. Keyed by the same
 *  Locale the rest of the app resolves, so switching the site language also
 *  switches every Clerk-rendered form and menu. */
const CLERK_LOCALIZATIONS: Record<Locale, typeof enUS> = {
  en: enUS,
  zh: zhCN,
  es: esES,
  hi: hiIN,
  fr: frFR,
};

const inter = Inter({ subsets: ["latin"], variable: "--font-inter", display: "swap" });
const playfair = Playfair_Display({ subsets: ["latin"], variable: "--font-playfair", display: "swap" });

export const metadata: Metadata = {
  title: "ResumeTailored",
  description:
    "A private office for your ambitions. Hiring for employers, tailored careers for candidates.",
  // RT logo favicon (generated by app/icon.tsx + app/apple-icon.tsx).
  icons: {
    icon: [{ url: "/icon" }],
    apple: [{ url: "/apple-icon" }],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const locale = resolveLocale(await getLocale());
  const messages = await getMessages();

  return (
    <ClerkProvider
      // Sensible post-auth defaults so a redirect resolves fast (the auth pages
      // still override per-flow). Reduces the redirect round-trips after login.
      signInFallbackRedirectUrl="/"
      signUpFallbackRedirectUrl="/"
      localization={CLERK_LOCALIZATIONS[locale]}
      appearance={{
        variables: {
          colorPrimary: "#C2870B", // gold rebrand
          colorBackground: "#0B0F19",
          colorText: "#FFFFFF",
          colorInputBackground: "#0B0F19",
          colorInputText: "#FFFFFF",
        },
      }}
    >
      <html lang={locale} className="dark">
        <head>
          {/* Resolve the Clerk Frontend API host early so clerk-js starts its
              DNS/TLS handshake immediately instead of after the bundle parses —
              trims the auth-init wait that used to show the blank gradient. */}
          <link rel="preconnect" href="https://clerk.resumetailored.com" crossOrigin="anonymous" />
          <link rel="dns-prefetch" href="https://clerk.resumetailored.com" />
        </head>
        <body className={`${inter.variable} ${playfair.variable} bg-navy text-cream font-sans antialiased`}>
          {/* Living gradient — fixed behind all content, shows through glass. */}
          <div className="gradient-bg" aria-hidden="true" />
          {/* Branded loader while clerk-js initializes — replaces the "blank
              gradient" wait with the RT loading screen on every route, all
              devices. It vanishes the moment Clerk is ready; the page content
              (server-rendered underneath) is then already there. */}
          <ClerkLoading>
            <LoadingScreen />
          </ClerkLoading>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <PWAProvider>
              <PlanPreviewBanner />
              {children}
            </PWAProvider>
          </NextIntlClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
