import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import { ClerkProvider, ClerkLoading } from "@clerk/nextjs";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { LoadingScreen } from "@/components/loading-screen";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter", display: "swap" });
const playfair = Playfair_Display({ subsets: ["latin"], variable: "--font-playfair", display: "swap" });

export const metadata: Metadata = {
  title: "ResumeTailored",
  description:
    "A private office for your ambitions. Hiring for employers, tailored careers for candidates.",
  // RT logo favicon (generated by app/icon.tsx + app/apple-icon.tsx).
  icons: {
    icon: [{ url: "/icon" }],
    apple: [{ url: "/apple-icon" }],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <ClerkProvider
      // Sensible post-auth defaults so a redirect resolves fast (the auth pages
      // still override per-flow). Reduces the redirect round-trips after login.
      signInFallbackRedirectUrl="/"
      signUpFallbackRedirectUrl="/"
      appearance={{
        variables: {
          colorPrimary: "#C2870B", // gold rebrand
          colorBackground: "#0B0F19",
          colorText: "#FFFFFF",
          colorInputBackground: "#0B0F19",
          colorInputText: "#FFFFFF",
        },
      }}
    >
      <html lang={locale} className="dark">
        <body className={`${inter.variable} ${playfair.variable} bg-navy text-cream font-sans antialiased`}>
          {/* Living gradient — fixed behind all content, shows through glass. */}
          <div className="gradient-bg" aria-hidden="true" />
          {/* Branded loader while clerk-js initializes — replaces the "blank
              gradient" wait with the RT loading screen on every route, all
              devices. It vanishes the moment Clerk is ready; the page content
              (server-rendered underneath) is then already there. */}
          <ClerkLoading>
            <LoadingScreen />
          </ClerkLoading>
          <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
          </NextIntlClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
