import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter", display: "swap" });
const playfair = Playfair_Display({ subsets: ["latin"], variable: "--font-playfair", display: "swap" });

export const metadata: Metadata = {
  title: "ResumeTailored",
  description:
    "A private office for your ambitions. Hiring for employers, tailored careers for candidates.",
  // RT logo favicon (generated by app/icon.tsx + app/apple-icon.tsx).
  icons: {
    icon: [{ url: "/icon" }],
    apple: [{ url: "/apple-icon" }],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: "#C2870B", // gold rebrand
          colorBackground: "#0B0F19",
          colorText: "#FFFFFF",
          colorInputBackground: "#0B0F19",
          colorInputText: "#FFFFFF",
        },
      }}
    >
      <html lang={locale} className="dark">
        <body className={`${inter.variable} ${playfair.variable} bg-navy text-cream font-sans antialiased`}>
          {/* Living gradient — fixed behind all content, shows through glass. */}
          <div className="gradient-bg" aria-hidden="true" />
          <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
          </NextIntlClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
