#!/usr/bin/env node
/**
 * build-fonts.js — one-off: self-host Inter + Fraunces + Syne (Latin subsets).
 *
 * Fetches the Google Fonts css2 stylesheet for the superset of families/weights
 * the site uses, keeps only the `latin` and `latin-ext` @font-face blocks
 * (the site has no CJK webfont — Chinese renders in system fonts), downloads
 * each referenced woff2 into public/fonts/, and rewrites the CSS to point at
 * those local files. Output: public/fonts.css + public/fonts/*.woff2.
 *
 * Re-run to refresh (idempotent-ish — overwrites). Requires outbound HTTPS.
 *   node scripts/build-fonts.js
 */
const fs = require('fs');
const path = require('path');

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const OUT_DIR = path.join(__dirname, '..', 'public', 'fonts');
const OUT_CSS = path.join(__dirname, '..', 'public', 'fonts.css');

// Superset of everything the site references (union across all pages).
const URL = 'https://fonts.googleapis.com/css2?'
  + 'family=Inter:wght@200;300;400;500;600;700;800;900'
  + '&family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;0,9..144,700;0,9..144,900;1,9..144,400;1,9..144,500;1,9..144,600'
  + '&family=Syne:wght@700;800;900'
  + '&display=swap';

// Keep only these subsets (comment labels in the Google CSS).
const KEEP = new Set(['latin', 'latin-ext']);

async function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const res = await fetch(URL, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error('google fonts css fetch failed: ' + res.status);
  const css = await res.text();

  // Split into (subset comment) + (@font-face { ... }) chunks.
  const blocks = [];
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let m;
  while ((m = re.exec(css)) !== null) blocks.push({ subset: m[1], body: m[2] });

  const urlToFile = new Map();
  let out = '/* Self-hosted fonts (Inter, Fraunces, Syne) — Latin subsets.\n'
    + '   Generated by scripts/build-fonts.js from Google Fonts. Do not edit by hand. */\n';
  let kept = 0;

  for (const b of blocks) {
    if (!KEEP.has(b.subset)) continue;
    kept++;
    const family = (b.body.match(/font-family:\s*'([^']+)'/) || [])[1] || 'font';
    const weight = (b.body.match(/font-weight:\s*([^;]+);/) || [])[1] || '400';
    const style = (b.body.match(/font-style:\s*([^;]+);/) || [])[1] || 'normal';
    const srcUrl = (b.body.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
    if (!srcUrl) continue;

    let localName = urlToFile.get(srcUrl);
    if (!localName) {
      // One variable woff2 per (family, style, subset) — stable name so
      // <link rel=preload> references never drift when this is regenerated.
      localName = `${family.toLowerCase()}-${style.trim()}-${b.subset}.woff2`;
      urlToFile.set(srcUrl, localName);
      const fontRes = await fetch(srcUrl, { headers: { 'User-Agent': UA } });
      if (!fontRes.ok) throw new Error('woff2 fetch failed: ' + srcUrl + ' -> ' + fontRes.status);
      const buf = Buffer.from(await fontRes.arrayBuffer());
      fs.writeFileSync(path.join(OUT_DIR, localName), buf);
      console.log(`  ↓ ${localName} (${(buf.length / 1024).toFixed(1)} KB)`);
    }
    // Rewrite this @font-face to point at the local file.
    const rewritten = b.body.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url(/fonts/${localName})`);
    out += '\n' + rewritten + '\n';
  }

  fs.writeFileSync(OUT_CSS, out);
  console.log(`\nWrote public/fonts.css — ${kept} @font-face blocks, ${urlToFile.size} woff2 files.`);
}

main().catch(e => { console.error(e); process.exit(1); });
